/* Controllers */

var emailControllers = angular.module('emailControllers', []);

emailControllers.controller('EmailListCtrl', ['$scope', '$http', '$filter',
	function EmailListCtrl($scope, $http, $filter) {
		"use strict";

		// whether to use tho old servicesFile generated by the simple csvtojson.py converter
		// or whether to use the current one generated by process.py
		$scope.old = false;
		$scope.numResults = 500;  // if this is omitted, the select input shows a blank by default
		var servicesFile;

		if ($scope.old)
			servicesFile = "uploads/servicesFile.old.json";
		else
			servicesFile = "uploads/servicesFile-all.json";

		$http.get(servicesFile).success(function(data) {
			$scope.offers = data;
		}).error(function(data) {
			$scope.errors = data;
			$scope.offers = {};
		});

		// Custom filter function for getting the UNIX timestamp from the offer for sorting
		$scope.getLastUpdatedFromOffer = function(offer) {
			return $scope.parseDate(offer.lastUpdated);
		};

		// Wrapper to native javascript method that parses Date strings
		// like "10/8/2013 21:58" into a UNIX timestamp (milliseconds since 1970).
		// For some reason, Date.parse() doesn't work inside angular.
		$scope.parseDate = function(d) {
			return Date.parse(d);
		};

		// Filter offers by lastUpdated and then limit to the numResults selected by user
		// Preview how these offers (edited by the user) will look
		$scope.previewMail = function() {
			var orderedOffers = $filter('orderBy')($scope.offers, $scope.getLastUpdatedFromOffer, true);
			var lastOffers = $filter('limitTo')(orderedOffers, $scope.numResults);
			alert(JSON.stringify( lastOffers ));
		};

		// Old convertCSV function from the Internet that I couldn't get to work
		var convertCSV = function() {
			$http.get(servicesFile).success(function(data) {
				csvObjects = CSV.parse(data);
				jsonText = JSON.stringify(csvObjects, null, '\t');
				alert( jsonText );
			}).error(function(data) {
				$scope.errors = data;
				$scope.offers = [];
			});
		};
	}
]);

emailControllers.controller('UploadCtrl', ['$scope', '$http',
	function UploadCtrl($scope, $http) {
		"use strict";
		$scope.formData = {};
		$scope.didSubmit = false;
		$scope.url = "/upload";

		$scope.change = function() {
			//names = [ 'communityFile', 'memberFile', 'servicesFile' ];
			names = [ 'servicesFile' ];
			for (var i = 0; i < names.length; i++) {
				var name = names[i];
				var el  = document.getElementById(name);
				alert(JSON.stringify(el));
				$scope.formData[name] = JSON.parse(el);
			}
		};

		$scope.showLoading = function() {
			$scope.didSubmit = true;
			$scope.alertType = "alert-success";
			$scope.submitAlert = "Loading...";
		};

		$scope.submit = function() {
			$scope.didSubmit = true;
			$scope.alertType = "alert-success";
			//$scope.change();
			var el  = document.getElementById('servicesFile');
			$scope.formData = el;

			//$scope.formData.communityFile = 'hello';
			$scope.submitAlert = JSON.stringify($scope.formData);

			$http.post({
				url: $scope.url,
				data: $scope.formData,
				headers: {'Content-Type': 'multipart/form-data'}
			}).success(function(data) {
				$scope.didSubmit = true;
				$scope.alertType = "alert-success";
				$scope.submitAlert = data;
			}).error(function(data) {
				$scope.didSubmit = true;
				$scope.alertType = "alert-error";
				$scope.submitAlert = data;
			});
		};
	}
]);

emailControllers.controller('loginCtrl', ['$scope',
	function loginCtrl($scope) {
		$scope.testVar = "hello world";
	}
]);
